### ISSUE TITLE
Just trying to create an issue

### ISSUE THREAD

**Issue by thematrjx** [shunyaek/shunyaek.github.io#3]
One doubt, is the Projects, About and Contact working I mean is there any landing page for the same or is it pending to be build.

Thanks

**Comment by HarshitDoshi** [comment]
No, these pages have not been built yet. I have planned the whole site to be rebuilt using ReactJS, but haven't really gotten around to actually doing it. For now, these pages have no links, they just point to a "#" link, so clicking on them won't take you anywhere.

😅

**Comment by thematrjx** [comment]
ohh cool
